### ISSUE TITLE
DELETE

### ISSUE THREAD

**Issue by MG1937** [DaxiaSecs/CyberMouses#10]
算了

**Comment by DaxiaSecs** [comment]
不知道你为什么会有这个问题，我并没有对外说过自己条件很松，危害很高吧，你可以让赛博鼠拿出证据，否则就是造谣。

他呢，是故意这样对外说，我吹嘘自己，吹嘘自己的漏洞，来营造我是勒索，我交的都是垃圾洞，厂商不应该给我一分钱的这个效果。然而我并没有吹嘘过哦，我提交给厂商的报告，有CVSS3，有场景，有前提描述，都是按照事实描述的。

当然，比如第二次提交本地成功过，所以确实误判了条件较简单，因为危害挺高(不方便细说) 想要5位数以上的奖金，后续了解到条件实际不是那么容易满足，也是按照厂商的高危接受了赏金。

最主要的是，这个漏洞，厂商直接绕过了我，先提前修复了。 至于危害高不高可以自行定夺。

**Comment by DaxiaSecs** [comment]
你应该好奇的是，提交漏洞本是白帽子和厂商之间的事情，本来这种东西也保密。

他为什么搞得好像他挖得漏洞一样，这不奇怪嘛？ 纯粹靠着自己意淫幻想得东西就去评价定性他人。

这个是他一致以来装大佬，吹牛逼得后遗症，太想当然了。
