### ISSUE TITLE
哦豁？

### ISSUE THREAD

**Issue by we1h0** [DaxiaSecs/CyberMouses#6]
![123](https://user-images.githubusercontent.com/36469846/174218783-b4236b69-8fa0-4d15-8b0d-dec1fa5358a9.jpeg)

**Comment by we1h0** [comment]
![456](https://user-images.githubusercontent.com/36469846/174218800-71642d60-3709-48f4-aa48-c454eb7a960c.jpeg)

**Comment by DaxiaSecs** [comment]
大聪明，兼听则明

**Comment by AdelramZheng** [comment]
> ![456](https://user-images.githubusercontent.com/36469846/174218800-71642d60-3709-48f4-aa48-c454eb7a960c.jpeg)

hhhhhhhh笑死
