### ISSUE TITLE
能不能分析下漂亮鼠为啥干了那么多年还是主管

### ISSUE THREAD

**Issue by wooyunvip** [DaxiaSecs/CyberMouses#8]
能不能分析下漂亮鼠为啥干了这么多年，挖了那么多垃圾漏洞还是个主管，而且还能退休

**Comment by Inv0k3r** [comment]
有没有可能是财务自由了呢，一个猜想不一定对

**Comment by DaxiaSecs** [comment]
晚点

**Comment by r007b34r** [comment]
因为国内安全厂商里蛀虫很多，举个简单例子，hackerone提交反射xss保底几十刀是有的，国内直接无视，不收。另外只要当个一官半职就开始摆架子玩小圈子搞情怀技术止步不前倚老卖老。
退一万步，如果一个人要真当自己是个主管，基本的肚量也得是有的，而不是为了热度玩命站队厂商，各种捏造事实带节奏。技术不够猥琐拿人品猥琐凑？
