### ISSUE TITLE
搞得安全圈乌烟瘴气🈶️意思？

### ISSUE THREAD

**Issue by shadow1ng** [DaxiaSecs/CyberMouses#9]

**Comment by DaxiaSecs** [comment]
问错地方了，这个问题你去问问赛博鼠，他要战我便战。
你作为白帽子，此时此刻按照厂商的收录要求和流程，正和厂商沟通着漏洞，这不是非常正常的事情？
另一个自称大佬的人，跳出来说这说那的，我暂且不说这关他啥事了，问题是他什么也不知道，漏洞也不是他挖的，利用条件，利用方式和利用危害都不知道，他就靠着自己意淫来的东西怼人，你说他又不是相关方，我也要恪守白帽子职业操守，我凭什么和他说细节和详情？然后他就纯意淫的来批驳同为白帽子的人，这是什么心态？
